{{
  tag="linklist"
  display="links"
  before_show="<div class='widget featured'>"
  show="<article class='pos-__position__'>"
  show="<a"
  show="__ifnewwindow__target='_blank'"
  show=" href='__url__'"
  show=">"
  show="<img src='__imageurl width='300' height='159'__' alt='' />"
  show="<span>__name__</span>"
  show="</a>"
  show="</article>"
  after_show="</div>"
}}