{{
  tag="linklist"
  display="links"
  before_show="<ul class='staff'>"
  show="<li class='staff-list'>"
  show="<a"
  show="__ifnewwindow__target='_blank'"
  show=" href='__url__'"
  show=">"
  show="<img src='__imageurl width='180' height='180'__' alt='' />"
  show="<h6 class='staff-name'>__name__</h6>"
  show="</a>"
  show="<span class='b4-role'>__description__</span>"
  show="</li>"
  after_show="</ul>"
}}