{{
  tag="linklist"
  display="links"
  before_show="<div class='staff'>"
  show="<article class='featured-item'>"
  show="<a"
  show="__ifnewwindow__target='_blank'"
  show=" href='__url__'"
  show=">"
  show="<img src='__imageurl width='180' height='180'__' alt='' />"
  show="<h4 class='staff-name'>__name__</h4>"
  show="</a>"
  show="<span class='b4-role'>__description__</span>"
  show="</article>"
  after_show="</div>"
}}