{{
  tag="event"
  display="list"
  order="recent"
  howmany="3"
  before_show="<div class='widget events div-col-3'>"
  show="<article class='div-col'>"
  show="<a href='__url__'>"
  show="<div class='date-wrap'>"
  show="<span class='month'>__eventstart format='M'__</span>"
  show="<span class='day'>__eventstartTwo format='j'__</span>"
  show="</div>"
  show="<h3>__title__</h3>"
  show="<p class='meta'>"
  show="<span class='times'>__eventtimes__</span>"
  show="<span class='location'>__location__</span>"
  show="</p>"
  show="</a>"
  show="</article>"  
  after_show="</div>"
}}